### ISSUE TITLE
Gestures folder

### ISSUE THREAD

**Issue by rakkeshravi** [harshbg/Sign-Language-Interpreter-using-Deep-Learning#4]
How to use the gestures folder created by you?

**Comment by rakkeshravi** [comment]
Only the gestures.db is provided.How to recover the gestures folder from the db provided?

**Comment by Xbot-me** [comment]
facing same problem here

**Comment by Xbot-me** [comment]
so looks like if you run create_gestures.py, this will create that folder for you. Silly me
