### ISSUE TITLE
Create gesture file problem

### ISSUE THREAD

**Issue by kshitipatel** [harshbg/Sign-Language-Interpreter-using-Deep-Learning#5]
line 71, in store_images
    contour = max(contours, key = cv2.contourArea)
error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:274: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'

**Comment by whiteblacksoft** [comment]
I have a same problem?

**Comment by jpg-130** [comment]
same problem

**Comment by harshbg** [comment]
You'll have to use create gestures file to generate all the gestures required.
