### ISSUE TITLE
Mobile integeration

### ISSUE THREAD

**Issue by nikhil19rathore99** [harshbg/Sign-Language-Interpreter-using-Deep-Learning#6]
Can it will be integrate in android??

**Comment by nikhil19rathore99** [comment]
In Readme u said that your model is deployed on cloud can i use your api if yes i cannot find your api??

**Comment by ChewBoonZhan** [comment]
Dear nikhil,

It is stated in the ReadMe under "features that can be added", not features that are added.
Hope this helps. The project is not on any API yet.
